spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related local APIs - PROD"
  contactDetails:
    name: "John Doe - Scrum master"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345