spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related local APIs - QA"
  contactDetails:
    name: "Ra - QA tester"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345